### ISSUE TITLE
[Feature request] Disable slice scores

### ISSUE THREAD

**Issue by MrTipson** [kinsi55/BeatSaber_Tweaks55#1]
#### Slice scores
The text that shows how much score the slice gave (/115) is not that useful for the player in real time and might also be distracting. Taking into account mods that provide an aggregated overview of the slice performance, I think it's beneficial to be able to turn per slice scoring off.

**Comment by kinsi55** [comment]
I dont find it distracting myself and find it useful in some locations to adjust in realtime but adding such an option is easy enough so why not.

**Comment by kinsi55** [comment]
Implemented now https://github.com/kinsi55/BeatSaber_Tweaks55/releases/tag/v0.0.9
