### ISSUE TITLE
Default bomb color is completely black

### ISSUE THREAD

**Issue by BlqzingIce** [kinsi55/BeatSaber_Tweaks55#10]
Due to the bomb color optimizations the default bomb color is now completely black instead of shaded, lowering bomb visibility greatly.  
Possible fix - Add a toggle to completely disable the bomb coloring patch, or a toggle for which shader the bombs use.  
(if I understood how the patch works)  
v0.3.6:
![image](https://user-images.githubusercontent.com/93460213/170813372-4f7d5f0d-fbc5-4cb7-9f7a-8c7fe958236c.png)
v0.3.7:
![image](https://user-images.githubusercontent.com/93460213/170813430-cdb72c3a-6e19-49aa-92c9-9ad93478de1d.png)
(Images were taken with the same config, I don't believe I have any other mods that would have affected the bombs)

**Comment by kinsi55** [comment]
Can you try clicking reset on the bomb color option
