### ISSUE TITLE
[Feature Request] Disable song and block slow down after miss

### ISSUE THREAD

**Issue by nev3rfail** [kinsi55/BeatSaber_Tweaks55#14]
I'm finding that slow down after a bad cut (assumingly for the player to realize mistake and concentrate) is very off-putting and it irritates the crap out of me because I'm losing my rhythm. Maybe there is an easy way to disable this behavior?

P.S.: It's weird that I am the only one having an issue with this, because I could not find anything related to this on google. Maybe I am missing something and the switch is already implemented in game and everybody knows about it, or i'm just using wrong keywords. -_- 

Thank you.

**Comment by kinsi55** [comment]
I have never heard of something like this, this most certainly is not a feature of the game. You must be experiencing some kind of game bug, have you tried asking for help in BSMG?
