### ISSUE TITLE
Static lights toggle resetting to On even when turned off previously

### ISSUE THREAD

**Issue by burritosoftware** [kinsi55/BeatSaber_Tweaks55#2]
When turning off the static lights toggle and restarting the game, the toggle appears on. The static lights are still off but the toggle is not properly reflecting if static lights are on or not.

**Comment by kinsi55** [comment]
This is known, I had not gotten around to fixing this yet but thank you for the report!

**Comment by kinsi55** [comment]
Fixed in new update
