### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by thojo0** [kinsi55/BeatSaber_Tweaks55#3]
I think you should maybe merge some of this features in Tweaks55.

- https://github.com/nate1280/BeatSaber-FireworksDisabler
- https://github.com/PulseLane/FastFail
- https://github.com/nate1280/BeatSaber-NoFailCheck

But if you do, don't forget to give them credits :ok_hand:.

**Comment by kinsi55** [comment]
I really do not like "stealing" others ideas and thus making their mod essentially obsolete, but from the list you presented, pretty much only disabling fireworks is relevant:

- No Fail nowadays can be pretty much left enabled all the time as it does not affect anything until you actually fail
- As for FastFail, I have an alternative plugin that is essentially the successor to it: https://github.com/kinsi55/CS_BeatSaber_GottaGoFast#hate-waiting-seconds-to-restart--exit-songs-me-too

Which leads me to disabling the Fireworks effect. I have not thought of that before, I'll ask Nate if he'd be OK with me adding that to tweaks.

**Comment by thojo0** [comment]
Yup, i think thats the right way to go. 👍🏽

**Comment by kinsi55** [comment]
I went a step further and spent (was too long) on only disabling the fireworks in campaigns, probably what most people will be caring about. I personally dont mind the PB fireworks
