### ISSUE TITLE
Typo in readme, description on ModAssistant

### ISSUE THREAD

**Issue by JasperJanin** [kinsi55/BeatSaber_Tweaks55#5]
The Mod Assistant description of this mod says
> A collection of various tweaks which by themselves are to simple for their own designated mods

"to" should be corrected to "too", in the readme, description of the repo and on Mod Assistant itself

**Comment by kinsi55** [comment]
Fixed in Repo, will fix for next modassistant release. thanks.

**Comment by ErisApps** [comment]
Fixed it in Mod Assistant for the current release in the meantime. 🙂
