### ISSUE TITLE
Cut Rumble

### ISSUE THREAD

**Issue by Bamux** [kinsi55/BeatSaber_Tweaks55#7]
First of all, thank you for your great work. Finally I found a mod that allows me to reduce the rumble. Currently, the reduction of the rumble does not affect the menu and also not when I cross the lightsabers. Would it be possible to extend the rumble reduction so that it is active everywhere?

I play with the old Oculus Touch Controllers, which unfortunately vibrate unbearably loud that I can't play with them without annoying other people in the same room.

**Comment by kinsi55** [comment]
For now your best bet is disabling Saberclash entirely (Thats what the effect is called when the sabers touch). I'll consider making that rumble configurable.

As for the Menu rumble, thats already pretty short - Is that really an issue? Would probably not be too hard to add a setting for it, just trying to not add super niche stuff into the already pretty big list of tweaks

**Comment by Bamux** [comment]
> As for the Menu rumble, thats already pretty short - Is that really an issue?

Thanks for your quick reply. It would also be enough for me if I can completely disable the rumble effect in the menu, if that is easier to implement. My controllers make really strange noises.  Here is an example of how loud my controllers get in the game Space Pirate Trainer.
https://youtu.be/gC80fgmOg10

**Comment by kinsi55** [comment]
But surely thats not the Rumble that you get from hovering UI elements right? I dont think I would add something in to disable Menu vibrations - Thats just a way too niche thing unfortunately, but here's a quick standalone mod that entirely disables haptics

[DisableUIRumble.zip](https://github.com/kinsi55/BeatSaber_Tweaks55/files/7826645/DisableUIRumble.zip)
:

**Comment by Bamux** [comment]
Not so extreme but loud enough that someone in the same room can wake up from the noise.

In the original Beat Saber release from May 2018, the vibrations were also much more subtle. I suspect in subsequent versions the vibrations were increased because the motors in the Quest 1/2 and Rift S controllers are weaker than those in the Oculus Touch controllers.

I wish Oculus had included the ability to globally reduce or disable force feedback in the software for the Oculus Rift, but unfortunately they have completely stopped development for the Oculus Rift software. In the software for the Oculus Quest, for example, there is the possibility to set the vibration effect globally for all games.

As a Rift 1 user for many games I always have to ask the developers if they can integrate this feature into the game (most of the smaller developer teams respond to customer feedback) or hope for mods like yours.

**Update:**
I tried the DisableUIRumble.dll but it had no effect on me in the menus the controller still vibrates when I go over menu buttons. Is there anything I need to do besides copy the DisableUIRumble.dl to the plugin folder?

**Comment by kinsi55** [comment]
Oh nah I messed up, this should work: [DisableUIRumble.zip](https://github.com/kinsi55/BeatSaber_Tweaks55/files/7829876/DisableUIRumble.zip)

**Comment by Bamux** [comment]
It works fantastic. Now I can play Beat Saber again in the evening. Thanks for your great work.

**Comment by Bamux** [comment]
I still have one small wish if it is not too much trouble. Is it possible to deactivate the vibration when contacting a wall so similar to disabling Saberclash?

**Comment by kinsi55** [comment]
Thats already an existing option

**Comment by Bamux** [comment]
Oh crap I somehow overlooked that :)

**Comment by naminode** [comment]
Thank you for your great work kinsi. Just out of curiosity , i noticed the rumble duration option is not around anymore. Is there any plan of adding that option back.

**Comment by naminode** [comment]
If that the case. I assume normal cut at 100% is equivalent to default vibration and duration when the mod is off. Can the max be extended over 100%. In previous version , I always have my vibration duration longer then default around (0.35sec~0.37sec)

**Comment by kinsi55** [comment]
For the lower two sliders I've allowed going over 100% because those are rather short by default and one might possibly want to extend those, but 100% for the cut rumble is like 1/10th of a second - Thats already pretty long.

Such long haptics can cause temporary loss of haptics or even tracking issues, specifically on faster maps, which is why I didnt really consider allowing the cut rumble to go above 100%

**Comment by naminode** [comment]
Maybe could allow user to increase above the limit. Provided initial warning notice is displayed on menu.

**Comment by kinsi55** [comment]
I can see myself allowing the slider to go up to effectively .2 seconds but definitely not beyond that
