### ISSUE TITLE
Add feature to disable camera noise/grain effect

### ISSUE THREAD

**Issue by MisterX2000** [kinsi55/BeatSaber_Tweaks55#8]
It would be nice to toggle the in game camera noise/grain effect as found in [ParticleOverdrive](https://github.com/Shadnix-was-taken/BeatSaber-ParticleOverdrive).
So then I would only need 1 mod.

**Comment by kinsi55** [comment]
That already exists, it's `Disable World Particles / Dust`

**Comment by MisterX2000** [comment]
Yeah, I know, but I meant something different.
The noise/grain/dither effect that is applied to the camera in Unity.
Here for example the implementation in the [CameraNoiseController.cs](https://github.com/Shadnix-was-taken/BeatSaber-ParticleOverdrive/blob/68f8eeb9100a88606faabdd875520654993fbcbc/ParticleOverdrive/Controllers/CameraNoiseController.cs).

I mean, I can always use both mods, but I thought this could be merged into this one, because I only miss this single feature and don't need the other ones to change particle effects.

**Comment by kinsi55** [comment]
Maybe this was once a thing (particle overdrive is a pretty old mod) but to my knowledge that doesn't exist nowadays

**Comment by kinsi55** [comment]
I just checked - Seems like I was wrong, its in fact still a thing. Its so suttle that I never noticed. Will add an option for it.

**Comment by kinsi55** [comment]
Will be included in the next update whenever I release that
